import Head from 'next/head'

import { Inter } from 'next/font/google'
import { TypeAnimation } from 'react-type-animation';
import { useState } from 'react';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import { Button } from "@mui/material";
import { UseMediaQueryOptions } from '@mui/material';
import useBreakpoint from '@/hooks/useBreakpoints';
import Router from 'next/router'  
import { LoginPage } from './login';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isFirstLineComplete,setIsFirstLineComplete] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Row>
          <div style={{display:'flex', alignItems: 'center', justifyContent:'center'}}>
              <h1 style={{fontSize:'3rem'}}>
                Papdi Chart
              </h1>
        </div>
        </Row>
        <Row>
          <div style={{display:'flex',justifyContent:'center'}}>
        <TypeAnimation sequence={[
        'Tell your story, with data'
      ]}
      wrapper="span"
      cursor={false}
      repeat={1}
      style={{ fontSize: '2em', display: 'inline-block' }}>
        </TypeAnimation>
        </div>
        </Row>
        <Row>
          <div style={{display:'flex', justifyContent:'center', marginTop:'2rem'}}>
          <Button onClick={()=>Router.push('/dashboards')} style={{background: 'linear-gradient(to right, #FF512F, #DD2476)!important', color:'white', borderRadius:'1rem', fontSize:'1rem', padding:'1rem'}}>Try Now</Button>
          </div>
        </Row>
        <Row>
          <div>
          <LoginPage></LoginPage>
          </div>
        </Row>
      </main>
    </>
  )
}
